### ISSUE TITLE
please use some alternate syntax

### ISSUE THREAD

**Issue by domenic** [matthewp/script-type-module#21]
Can you use type="module-polyfill" or something? Given that we're still working on the implementations, it would be great to not constrain implementations to be compatible with the polyfill if people start using this.

This has been a real problem in the past: we had to rename all web components methods since polyfills were using semantics that became incorrect as we moved toward cross browser compat.

**Comment by matthewp** [comment]
I've changed it to module-polyfill for now.  When do you think this will be safe to polyfill? Polyfilling features that haven't shipped is pretty common, [here's one](https://github.com/ljharb/System.global) for `global`, for example. Or are you just against polyfilling in general?

I surely don't want to pollute the ecosystem with incorrect semantics but at the same time I do want this to transparently use the native implementation when they are available. I'm already [testing for native support](https://github.com/matthewp/script-type-module/blob/master/src/window/utils.js#L1) and bailing out. Although I haven't been able to verify that this works yet because of [this bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9011688/) in Edge.

Anyways, maybe the path forward is to leave it as an alternative type until it ships in one or two evergreen browsers and then switch back over to "module".

**Comment by domenic** [comment]
Responsible and safe polyfilling is a complex topic that I plan to write more about at length in the future. Suffice to say that I am not against polyfills in general, but I think that recent trends have been moving much more toward harm than help.

So specifically, I think it would be safe to do a polyfill that squats on the standard name once this is shipping in at least two, preferably three browsers.

> I'm already testing for native support and bailing out.

I think it is almost never safe to do a conditional polyfill. *Please* do not test for native support and bail out. That is the biggest antipattern imaginable, as it guarantees that implementations will be constrained by usage. Just this week at TC39 we discussed how many problems such code has caused in the past, and how we'd like to figure out some way of encouraging (through the design of the language and its libraries) unconditional polyfills instead of conditional ones.

It could imaginably be safe in cases like IE8, where you're sure that most code is not using the polyfill (so the benefit is large) and your users are definitely testing there (so the potential harm is small). But it's 100% unsafe for a feature like this.

> Anyways, maybe the path forward is to leave it as an alternative type until it ships in one or two evergreen browsers and then switch back over to "module".

I'd definitely wait for two, and even then I would ask that you remove the conditionalness until we have three or more.

**Comment by matthewp** [comment]
Ok, thanks a lot for your input. I can see now where conditional polyfilling would be problematic, so I'll remove that as well and keep with `type="module-polyfill"`.
